### ISSUE TITLE
Issue with ".detach().numpy()" when using entropy_optim

### ISSUE THREAD

**Issue by mriganktiwari** [vaibkumr/prompt-optimizer#3]
Hi,

When I try to optimise a prompt using ```entropy_optim```, it gives an error 

```
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

when executing [line 83](https://github.com/vaibkumr/prompt-optimizer/blob/7ebd279cd166824b93b8c37eddb6c31259c77686/prompt_optimizer/poptim/entropy_optim.py#L83)

Although, I the workaround of adding ```.cpu()``` before ```.detach()``` works, **is there any other solution without making this change**?

**Comment by vaibkumr** [comment]
Thanks for pointing this out. For GPU machines tensors must move to cpu before converting to numpy.

Fixed here: https://github.com/vaibkumr/prompt-optimizer/pull/4
